apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rakesh-reddit-clone-app
  template:
    metadata:
      labels:
        app: rakesh-reddit-clone-app
    spec:
      containers:
        - name: rakesh-reddit-clone-app
          image: rakeshdhub/reddit-clone-pipeline:
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
